name: Deploy to ITU Server

on:
  push:
    branches:
      - itu-server-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to ITU server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ITU_SSH_HOST }}
          username: ${{ secrets.ITU_SSH_USERNAME }}
          key: ${{ secrets.ITU_SSH_KEY }}
          port: ${{ secrets.ITU_SSH_PORT }}
          source: "public/*"
          target: "/home/vcampteam/vcampteam.itu.edu.tr/public_html"
          strip_components: 1
          rm: false