name: Deploy to ITU Server

on:
  push:
    branches:
      - itu-server-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete --exclude='.git/'
          path: public/
          remote_path: /itu/users/vcampteam/vcampteam.itu.edu.tr/public_html/
          remote_host: ${{ secrets.ITU_SSH_HOST }}
          remote_user: ${{ secrets.ITU_SSH_USERNAME }}
          remote_key: ${{ secrets.ITU_SSH_KEY }}
          remote_port: ${{ secrets.ITU_SSH_PORT }}
